# Generated by Django 4.1.2 on 2023-06-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecn', '0003_remove_cursos_id_area_delete_modalcursos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='id',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='url_amigable',
        ),
        migrations.AddField(
            model_name='noticia',
            name='id_noticia',
            field=models.IntegerField(default=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
