# Generated by Django 4.1.2 on 2023-06-23 21:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ecn', '0005_alter_noticia_id_noticia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='id_noticia',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
