# Generated by Django 4.1.2 on 2023-07-05 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecn', '0006_alter_noticia_id_noticia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
